platform:ios, '7.0'

pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'Reachability'
pod 'FMDB'
pod 'FPPopover'
pod 'JGActionSheet'
pod 'MJRefresh'
pod 'TSLibraryImport'
pod 'GCDWebServer'
pod 'CocoaAsyncSocket' 